 - name: Install the php and mariadb packages on hosts in the dev, test, and prod
   hosts: dev,test,prod
   become: true
   tasks:
     - name: Install the packages on dev, test, and prod 
       ansible.builtin.dnf:
         name: 
           - php
           - mariadb
         state: present
 - name: Install RPM Development Tools package group on hosts in the dev 
   hosts: dev
   become: true
   tasks:
     - name: Install RPM Development Tools" package group on hosts in the dev 
       ansible.builtin.dnf:
         name: "@RPM Development Tools"
         state: installed
     - name: Update all packages to the latest version on hosts in the dev 
       ansible.builtin.dnf:
         name: "*"
         state: latest 