---
- name: Install HAProxy
  ansible.builtin.dnf:
    name: haproxy
    state: present

- name: Deploy HAProxy configuration
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'

- name: Validate HAProxy configuration
  ansible.builtin.command:
    cmd: haproxy -c -f /etc/haproxy/haproxy.cfg
  changed_when: false

- name: Enable and start HAProxy
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: true

- name: Allow HTTP
  ansible.posix.firewalld:
    service: http
    permanent: true
    immediate: true
    state: enabled
