---
- name: Install Apache and PHP
  ansible.builtin.dnf:
    name:
      - httpd
      - php
    state: present

- name: Create PHP information page
  ansible.builtin.copy:
    dest: /var/www/html/hello.php
    content: |
      <?php
      echo "Hello PHP World from " . gethostname() . "<br>";
      phpinfo();
      ?>
    owner: root
    group: root
    mode: '0644'

- name: Start and enable Apache
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true

- name: Allow HTTP
  ansible.posix.firewalld:
    service: http
    permanent: true
    immediate: true
    state: enabled
